"""
Export labelled charts as PNG only.

  python scripts/viz.py

Change titles, axis labels, legends, captions: edit exports/brief_copy.json then rerun.
Do not edit this file for wording.
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import pandas as pd
from matplotlib.collections import PatchCollection
from matplotlib.colors import Normalize
from matplotlib.patches import PathPatch
from matplotlib.path import Path as MPath

STEP_ROOT = Path(__file__).resolve().parents[1]   # step_1/
ROOT = STEP_ROOT.parent                             # repo root (data/, raw/ live here)
DATA = ROOT / "data"
RAW = ROOT / "raw"
EXPORTS = STEP_ROOT / "exports"
FIGURES = EXPORTS / "figures"
COPY_PATH = EXPORTS / "brief_copy.json"

PAPER = "#FFFFFF"
INK = "#1F2937"
MUTED = "#6B7280"
PPE = "#2563EB"
HOUSE = "#D97706"
BAND = "#BFDBFE"
NEW = "#0891B2"
ZD = "#64748B"
NEG = "#D97706"
POS = "#2563EB"
MISS = "#E5E7EB"
LINE = "#D1D5DB"
SOURCE = "Source: OCSTAT, Canton of Geneva"
SOURCE_CALC = "Source: OCSTAT, Canton of Geneva; author's calculations"
OLD_PNG = (
    "01_ppe_m2",
    "02_houses_object",
    "03_map_ppe_2024",
    "04_volume_new_existing",
)
DPI = 300


def fmt_int(n) -> str:
    return f"{int(round(n)):,}"


def geo_id_str(s: pd.Series) -> pd.Series:
    out = []
    for v in s:
        if v is None or (isinstance(v, float) and pd.isna(v)) or str(v).strip() == "":
            out.append(pd.NA)
            continue
        t = str(v).strip()
        if t.endswith(".0") and t[:-2].lstrip("-").isdigit():
            t = t[:-2]
        if t.lstrip("-").isdigit():
            out.append(f"{int(t):04d}")
        else:
            out.append(t)
    return pd.Series(out, index=s.index, dtype="string")


def latest(pattern: str) -> Path:
    files = sorted(p for p in RAW.rglob(pattern) if not p.name.startswith("~$"))
    if not files:
        raise FileNotFoundError(pattern)
    return files[-1]


def load() -> dict:
    price = pd.read_csv(DATA / "fact_price.csv")
    vol = pd.read_csv(DATA / "fact_volume.csv")
    price["geo_id"] = geo_id_str(price["geo_id"])
    vol["geo_id"] = geo_id_str(vol["geo_id"])
    for df in (price, vol):
        if "is_provisional" not in df.columns:
            df["is_provisional"] = 0
        df["is_provisional"] = df["is_provisional"].fillna(0).astype(int)
        df["year"] = df["year"].astype(int)
    copy = json.loads(COPY_PATH.read_text(encoding="utf-8"))
    gj = json.loads(latest("*_sitg_cad_commune.geojson").read_text(encoding="utf-8"))
    return {"price": price, "vol": vol, "copy": copy, "gj": gj}


def ppe_m2(
    price: pd.DataFrame,
    *,
    geo: str | None = "0000",
    condition: str = "existing",
    market: str = "libre",
    communes_only: bool = False,
) -> pd.DataFrame:
    q = (
        (price.source == "T_05_05_1_4_03")
        & (price.market == market)
        & (price.condition == condition)
        & (price.is_provisional == 0)
        & price["median"].notna()
    )
    out = price.loc[q].copy()
    if communes_only:
        out = out[out.geo_id.notna() & (out.geo_id != "0000")]
    elif geo is not None:
        out = out[out.geo_id == geo]
    return out.sort_values("year")


def house_object(price: pd.DataFrame, *, geo: str | None = "0000", communes_only: bool = False) -> pd.DataFrame:
    q = (price.source == "T_05_05_1_3_03") & (price.is_provisional == 0) & price["median"].notna()
    out = price.loc[q].copy()
    if communes_only:
        out = out[out.geo_id.notna() & (out.geo_id != "0000")]
    elif geo is not None:
        out = out[out.geo_id == geo]
    return out.sort_values("year")


def kpis(price: pd.DataFrame, vol: pd.DataFrame, params: dict) -> dict:
    ppe = ppe_m2(price)
    canton = ppe[ppe.year == 2024].iloc[0]
    city = ppe_m2(price, geo="6621")
    city = city[city.year == 2024].iloc[0]
    comm = ppe_m2(price, geo=None, communes_only=True)
    comm24 = comm[comm.year == 2024]
    top = comm24.sort_values("median", ascending=False).iloc[0]
    bot = comm24.sort_values("median", ascending=True).iloc[0]
    house = house_object(price)
    house = house[house.year == 2024].iloc[0]
    vy = vol[(vol.freq == "Y") & (vol.year == 2024) & (vol.is_provisional == 0)].set_index("type_id")["n"]
    new24 = ppe_m2(price, condition="new")
    new24 = new24[new24.year == 2024].iloc[0]
    zd24 = ppe_m2(price, condition="all", market="zd")
    zd24 = zd24[zd24.year == 2024]
    lib_all = ppe_m2(price, condition="all", market="libre")
    lib_all = lib_all[lib_all.year == 2024]
    budget = int(params.get("budget_chf", 800_000))
    cagr_years = int(params.get("cagr_years", 10))
    premium = 100 * (float(city["median"]) / float(canton["median"]) - 1)
    new_prem = 100 * (float(new24["median"]) / float(canton["median"]) - 1)
    return {
        "end_year": 2024,
        "start_year": 2024 - cagr_years,
        "cagr_years": cagr_years,
        "budget_chf": budget,
        "canton_m2": float(canton["median"]),
        "city_m2": float(city["median"]),
        "premium_pct": premium,
        "new_m2": float(new24["median"]),
        "new_prem_pct": new_prem,
        "n_communes": int(len(comm24)),
        "top_commune": str(top["geo_label"]),
        "top_m2": float(top["median"]),
        "bottom_commune": str(bot["geo_label"]),
        "bottom_m2": float(bot["median"]),
        "house_chf": float(house["median"]),
        "house_m": float(house["median"]) / 1e6,
        "h_ex": int(vy["house_existing"]),
        "h_new": int(vy["house_new"]),
        "p_ex": int(vy["ppe_existing"]),
        "p_new": int(vy["ppe_new"]),
        "zd_m2": float(zd24.iloc[0]["median"]) if len(zd24) else None,
        "libre_all_m2": float(lib_all.iloc[0]["median"]) if len(lib_all) else None,
    }


def format_tree(obj, ctx: dict):
    if isinstance(obj, str):
        try:
            return obj.format(**ctx)
        except (KeyError, IndexError, ValueError):
            return obj
    if isinstance(obj, list):
        return [format_tree(x, ctx) for x in obj]
    if isinstance(obj, dict):
        return {k: format_tree(v, ctx) for k, v in obj.items()}
    return obj


def fill_copy(copy: dict, k: dict) -> dict:
    ctx = {
        "canton_m2": fmt_int(k["canton_m2"]),
        "city_m2": fmt_int(k["city_m2"]),
        "premium_pct": f"{k['premium_pct']:.1f}",
        "new_m2": fmt_int(k["new_m2"]),
        "new_prem_pct": f"{k['new_prem_pct']:.1f}",
        "top_commune": k["top_commune"],
        "top_m2": fmt_int(k["top_m2"]),
        "bottom_commune": k["bottom_commune"],
        "bottom_m2": fmt_int(k["bottom_m2"]),
        "house_m": f"{k['house_m']:.2f}",
        "n_communes": str(k["n_communes"]),
        "h_ex": fmt_int(k["h_ex"]),
        "h_new": fmt_int(k["h_new"]),
        "p_ex": fmt_int(k["p_ex"]),
        "p_new": fmt_int(k["p_new"]),
        "budget": fmt_int(k["budget_chf"]),
        "cagr_years": str(k["cagr_years"]),
        "start_year": str(k["start_year"]),
        "end_year": str(k["end_year"]),
        "zd_m2": fmt_int(k["zd_m2"]) if k["zd_m2"] is not None else "",
        "libre_all_m2": fmt_int(k["libre_all_m2"]) if k["libre_all_m2"] is not None else "",
    }
    return format_tree(json.loads(json.dumps(copy)), ctx)


def setup_mpl() -> None:
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["DejaVu Sans", "Segoe UI", "Arial"],
            "figure.facecolor": PAPER,
            "savefig.facecolor": PAPER,
            "axes.unicode_minus": False,
        }
    )


def style_ax(ax, ylabel: str | None = None, xlabel: str | None = None, grid: str = "y") -> None:
    ax.set_facecolor(PAPER)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color(LINE)
    ax.spines["bottom"].set_color(LINE)
    ax.tick_params(colors=MUTED, labelsize=12)
    if ylabel:
        ax.set_ylabel(ylabel, color=MUTED, fontsize=13)
    if xlabel:
        ax.set_xlabel(xlabel, color=MUTED, fontsize=13)
    if grid:
        ax.grid(axis=grid, color=LINE, linewidth=0.7)
    ax.set_axisbelow(True)


def year_axis(ax) -> None:
    ax.xaxis.set_major_locator(mticker.MaxNLocator(integer=True))


def caption(fig: plt.Figure, note: str, *, derived: bool = False) -> None:
    src = SOURCE_CALC if derived else SOURCE
    fig.text(0.01, 0.012, f"{note}\n{src}", fontsize=10, color=MUTED, va="bottom")


def title(ax, text: str) -> None:
    ax.set_title(text, loc="left", color=INK, fontsize=17, fontweight="bold", pad=12)


def ch(copy: dict, chart_id: str) -> dict:
    return copy["charts"][chart_id]


def plot_interval(ax, df: pd.DataFrame, *, color: str, xcols: tuple[str, str, str], scale: float = 1.0) -> None:
    y = list(range(len(df)))
    lo, mid, hi = xcols
    ax.hlines(y, df[lo] / scale, df[hi] / scale, color=color, linewidth=3.2, alpha=0.9)
    ax.scatter(df[mid] / scale, y, color=INK, s=28, zorder=3)
    ax.set_yticks(y, df["geo_label"].astype(str))
    ax.tick_params(axis="y", labelsize=9, colors=INK)


def avg_ticket_quarter(vol: pd.DataFrame, year: int, quarter: int) -> pd.DataFrame:
    order = ["house_existing", "house_new", "ppe_existing", "ppe_new"]
    df = vol[
        (vol.source == "T_05_05_1_1_01")
        & (vol.freq == "Q")
        & (vol.year == year)
        & (vol.quarter == quarter)
        & (vol.type_id.isin(order))
    ][["type_id", "n", "value_chf"]].copy()
    df["avg_chf"] = df["value_chf"] / df["n"]
    return df.set_index("type_id").loc[order].reset_index()


def latest_quarter(price: pd.DataFrame, vol: pd.DataFrame) -> tuple[int, int]:
    q_price = price[
        (price.source == "T_05_05_1_1_02")
        & (price.freq == "Q")
        & (price["median"].notna())
        & (price.type_id.isin(["house_existing", "ppe_existing"]))
    ][["year", "quarter"]].drop_duplicates()
    q_vol = vol[
        (vol.source == "T_05_05_1_1_01")
        & (vol.freq == "Q")
        & (vol["n"].notna())
        & (vol["value_chf"].notna())
        & (vol.type_id.isin(["house_existing", "house_new", "ppe_existing", "ppe_new"]))
    ][["year", "quarter"]].drop_duplicates()
    q = q_price.merge(q_vol, on=["year", "quarter"])
    last = q.sort_values(["year", "quarter"]).iloc[-1]
    return int(last["year"]), int(last["quarter"])


def prev_quarter(year: int, quarter: int) -> tuple[int, int]:
    return (year - 1, 4) if quarter == 1 else (year, quarter - 1)


def existing_range_quarter(price: pd.DataFrame, year: int, quarter: int) -> pd.DataFrame:
    order = ["ppe_existing", "house_existing"]
    df = price[
        (price.source == "T_05_05_1_1_02")
        & (price.freq == "Q")
        & (price.year == year)
        & (price.quarter == quarter)
        & (price.type_id.isin(order))
        & (price["median"].notna())
    ][["type_id", "n", "p25", "median", "p75"]].copy()
    return df.set_index("type_id").loc[order].reset_index()


def qoq_badge(pct: float) -> tuple[str, str, str]:
    if abs(pct) < 0.05:
        return f"{pct:.1f}% QoQ", "#57534E", "#E7E5E4"
    if pct > 0:
        return f"▲ +{pct:.1f}% QoQ", "#166534", "#DCFCE7"
    return f"▼ {pct:.1f}% QoQ", "#B91C1C", "#FEE2E2"


def fig_q_latest_avg_ticket(price: pd.DataFrame, vol: pd.DataFrame, copy: dict) -> plt.Figure:
    year, quarter = latest_quarter(price, vol)
    c = ch(copy, "09_q_latest_avg_ticket")
    df = avg_ticket_quarter(vol, year, quarter)
    prev = avg_ticket_quarter(vol, year - 1, quarter).rename(columns={"avg_chf": "avg_chf_prev"})
    df = df.merge(prev[["type_id", "avg_chf_prev"]], on="type_id", how="left")
    df["yoy_pct"] = (df["avg_chf"] / df["avg_chf_prev"] - 1) * 100

    segment_labels = {
        "house_existing": f"{c['label_house']} {c['label_existing']}",
        "house_new": f"{c['label_house']} {c['label_new']}",
        "ppe_existing": f"{c['label_ppe']} {c['label_existing']}",
        "ppe_new": f"{c['label_ppe']} {c['label_new']}",
    }
    labels = [f"{segment_labels[row.type_id]}\n(n={fmt_int(row.n)})" for row in df.itertuples()]
    colors = ["#059669", "#6EE7B7", "#3B82F6", "#93C5FD"]

    fig, ax = plt.subplots(figsize=(9.0, 5.8))
    x = range(len(df))
    ax.bar(x, df["avg_chf"], color=colors, width=0.68)
    label_y = max(df["avg_chf"]) * 0.035
    for i, row in df.iterrows():
        y = row["avg_chf"] + label_y
        if pd.notna(row["yoy_pct"]):
            pos = row["yoy_pct"] >= 0
            badge_bg = "#DCFCE7" if pos else "#FEE2E2"
            badge_fg = "#166534" if pos else "#B91C1C"
            sign = "+" if pos else ""
            sym = "▲" if pos else "▼"
            ax.annotate(
                f"{sym} {sign}{row['yoy_pct']:.1f}%",
                xy=(i, y),
                xytext=(0, 38),
                textcoords="offset points",
                ha="center",
                va="bottom",
                fontsize=11,
                color=badge_fg,
                bbox={"boxstyle": "round,pad=0.3", "facecolor": badge_bg, "edgecolor": "none"},
            )
        ax.text(
            i,
            y,
            f"{row['avg_chf'] / 1e6:.2f}M CHF",
            ha="center",
            va="bottom",
            fontsize=15,
            color=INK,
            fontweight="bold",
        )
    ax.set_xticks(list(x), labels, fontsize=11)
    style_ax(ax, c["ylabel"])
    ax.set_ylim(0, max(df["avg_chf"]) * 1.35)
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _p: f"{v/1e6:.1f}M"))
    ax.grid(axis="x", visible=False)
    fig.subplots_adjust(left=0.12, right=0.97, top=0.76, bottom=0.22)
    fig.text(0.01, 0.98, c["title"], fontsize=20, color=INK, fontweight="bold", va="top")
    fig.text(0.01, 0.89, c["subtitle"], fontsize=13, color=MUTED, va="top", style="italic")
    ax.text(0.98, 0.98, f"Q{quarter} {year}", transform=ax.transAxes,
            fontsize=13, color=MUTED, ha="right", va="top")
    ax.text(0.98, 0.90, f"YoY vs Q{quarter} {year - 1}", transform=ax.transAxes,
            fontsize=11, color=MUTED, ha="right", va="top")
    fig.text(0.01, 0.06, c["footnote"], fontsize=10, color=MUTED, va="top")
    return fig


def fig_ppe_trend(price: pd.DataFrame, copy: dict) -> plt.Figure:
    s = ppe_m2(price)
    c = ch(copy, "01_ppe_trend")
    fig, ax = plt.subplots(figsize=(10.2, 5.7))
    ax.fill_between(s.year, s.p25, s.p75, color=BAND, linewidth=0, label=c["legend_iqr"])
    ax.plot(s.year, s["median"], color=PPE, linewidth=2.4, label=c["legend_median"])
    style_ax(ax, c["ylabel"])
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
    year_axis(ax)
    ax.set_xlim(int(s.year.min()) - 0.4, int(s.year.max()) + 0.4)
    fig.subplots_adjust(left=0.08, right=0.97, top=0.82, bottom=0.16)
    fig.text(0.01, 0.98, c["title"], fontsize=17, color=INK,
             fontweight="bold", va="top")
    fig.text(0.01, 0.06, c["note"], fontsize=10, color=MUTED, va="top")
    return fig


def fig_city_vs_canton(price: pd.DataFrame, copy: dict) -> plt.Figure:
    canton = ppe_m2(price)
    city = ppe_m2(price, geo="6621")
    m = canton[["year", "median"]].merge(city[["year", "median"]], on="year", suffixes=("_canton", "_city"))
    last = m.sort_values("year").iloc[-1]
    c = ch(copy, "02_city_vs_canton")
    fig, ax = plt.subplots(figsize=(10.2, 5.7))
    ax.plot(m.year, m["median_canton"], color=MUTED, linewidth=2.2, label=c["legend_canton"])
    ax.plot(m.year, m["median_city"], color=PPE, linewidth=2.4, label=c["legend_city"])
    style_ax(ax, c["ylabel"])
    title(ax, c["title"])
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
    year_axis(ax)
    ax.annotate(
        c["kpi_label"],
        xy=(last["year"], last["median_city"]),
        xytext=(-86, 12),
        textcoords="offset points",
        fontsize=9,
        color=PPE,
        fontweight="bold",
    )
    fig.subplots_adjust(left=0.12, right=0.97, top=0.86, bottom=0.20)
    caption(fig, c["note"])
    return fig


def _rings(geom) -> list:
    t = geom.get("type")
    if t == "Polygon":
        return [geom["coordinates"]]
    if t == "MultiPolygon":
        return list(geom["coordinates"])
    return []


def _patch(ring) -> PathPatch | None:
    exterior = ring[0]
    verts = [(float(x), float(y)) for x, y, *_ in exterior]
    if len(verts) < 3:
        return None
    codes = [MPath.MOVETO] + [MPath.LINETO] * (len(verts) - 1)
    return PathPatch(MPath(verts, codes))


def fig_ppe_map(gj: dict, price: pd.DataFrame, copy: dict) -> plt.Figure:
    vals = ppe_m2(price, geo=None, communes_only=True)
    vals = vals[vals.year == 2024][["geo_id", "geo_label", "median", "n"]]
    lookup = dict(zip(vals["geo_id"].astype(str), vals["median"].astype(float)))
    cmap = plt.cm.Blues
    vmin, vmax = min(lookup.values()), max(lookup.values())
    norm = Normalize(vmin=vmin, vmax=vmax)
    colored, grey = [], []
    for ft in gj["features"]:
        props = ft["properties"]
        name = str(props.get("commune") or "")
        bfs = props.get("no_com_federal")
        gid = "6621" if name.startswith("Genève-") else (f"{int(bfs):04d}" if bfs is not None else None)
        med = lookup.get(gid) if gid else None
        for poly in _rings(ft["geometry"]):
            patch = _patch(poly)
            if patch is None:
                continue
            if med is None:
                grey.append(patch)
            else:
                patch.set_facecolor(cmap(norm(med)))
                colored.append(patch)
    fig, ax = plt.subplots(figsize=(8.8, 8.2))
    ax.add_collection(PatchCollection(grey, facecolor=MISS, edgecolor="white", linewidths=0.4, match_original=False))
    ax.add_collection(PatchCollection(colored, match_original=True, edgecolor="white", linewidths=0.4))
    ax.set_aspect("equal")
    ax.autoscale()
    ax.axis("off")
    c = ch(copy, "03_ppe_map")
    title(ax, c["title"])
    sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
    cb = fig.colorbar(sm, ax=ax, fraction=0.035, pad=0.02, shrink=0.65)
    cb.ax.tick_params(labelsize=8, colors=MUTED)
    cb.set_label(c["ylabel"], fontsize=8, color=MUTED)
    fig.subplots_adjust(left=0.02, right=0.90, top=0.90, bottom=0.12)
    caption(fig, c["note"])
    return fig


def _centroid(geom) -> tuple[float, float]:
    """Average of exterior ring vertices — rough centroid."""
    xs, ys = [], []
    for ring in _rings(geom):
        for x, y, *_ in ring[0]:
            xs.append(float(x))
            ys.append(float(y))
    return (sum(xs) / len(xs), sum(ys) / len(ys)) if xs else (0, 0)


def _load_lake() -> list[list[float]] | None:
    """Load Lac Léman polygon if available."""
    import json as _json
    lake_path = ROOT / "raw" / "lake_leman.geojson"
    if not lake_path.exists():
        return None
    with open(lake_path, encoding="utf-8") as f:
        feat = _json.load(f)
    geom = feat.get("geometry", {})
    if geom.get("type") == "Polygon":
        return geom["coordinates"][0]
    if geom.get("type") == "MultiPolygon":
        return geom["coordinates"][0][0]
    return None


def _labeled_map(
    gj: dict,
    data: pd.DataFrame,
    prev_data: pd.DataFrame | None,
    c: dict,
    cmap,
    value_fmt,
    canton_med: float | None = None,
) -> plt.Figure:
    """Choropleth with commune labels, YoY badges, lake overlay."""
    lookup = dict(zip(data["geo_id"].astype(str), data["median"].astype(float)))
    n_lookup = dict(zip(data["geo_id"].astype(str), data["n"].astype(int)))
    label_lookup = dict(zip(data["geo_id"].astype(str), data["geo_label"].astype(str)))

    prev_lookup: dict = {}
    if prev_data is not None and len(prev_data):
        prev_lookup = dict(zip(prev_data["geo_id"].astype(str), prev_data["median"].astype(float)))

    vmin, vmax = (min(lookup.values()), max(lookup.values())) if lookup else (0, 1)
    norm = Normalize(vmin=vmin * 0.95, vmax=vmax * 1.05)

    colored, grey = [], []
    centroids: dict[str, tuple[float, float]] = {}

    for ft in gj["features"]:
        props = ft["properties"]
        name = str(props.get("commune") or "")
        bfs = props.get("no_com_federal")
        gid = "6621" if name.startswith("Genève-") else (f"{int(bfs):04d}" if bfs is not None else None)
        med = lookup.get(gid) if gid else None

        if gid and gid not in centroids:
            centroids[gid] = _centroid(ft["geometry"])
        elif gid and gid in centroids:
            cx, cy = _centroid(ft["geometry"])
            ox, oy = centroids[gid]
            centroids[gid] = ((ox + cx) / 2, (oy + cy) / 2)

        for poly in _rings(ft["geometry"]):
            patch = _patch(poly)
            if patch is None:
                continue
            if med is None:
                grey.append(patch)
            else:
                patch.set_facecolor(cmap(norm(med)))
                colored.append(patch)

    fig, ax = plt.subplots(figsize=(12.0, 7.5))

    if grey:
        ax.add_collection(PatchCollection(
            grey, facecolor=MISS, edgecolor="white",
            linewidths=0.5, match_original=False))
    if colored:
        ax.add_collection(PatchCollection(
            colored, match_original=True,
            edgecolor="white", linewidths=0.5))

    ax.set_aspect("equal")
    ax.autoscale()
    ax.axis("off")

    lake_coords = _load_lake()
    if lake_coords:
        xlo_c, xhi_c = ax.get_xlim()
        ylo_c, yhi_c = ax.get_ylim()
        pad = 0.02
        lake_clipped = [
            (x, y) for x, y, *_ in lake_coords
            if xlo_c - pad <= x <= xhi_c + pad and ylo_c - pad <= y <= yhi_c + pad
        ]
        if len(lake_clipped) > 3:
            codes = [MPath.MOVETO] + [MPath.LINETO] * (len(lake_clipped) - 1)
            lake_patch = PathPatch(
                MPath(lake_clipped, codes),
                facecolor="#BFDBFE", edgecolor="none", alpha=0.35, zorder=5,
            )
            ax.add_patch(lake_patch)

    xlo, xhi = ax.get_xlim()
    ylo, yhi = ax.get_ylim()
    span_x = xhi - xlo
    span_y = yhi - ylo

    if lake_coords:
        lake_center_x = (xlo + xhi) / 2 + span_x * 0.05
        lake_center_y = yhi - span_y * 0.08
        ax.text(lake_center_x, lake_center_y,
                "Lac L\u00e9man",
                ha="center", va="center", fontsize=14,
                color="#2563EB", style="italic", alpha=0.6, zorder=6)

    OFFSETS: dict[str, tuple[float, float]] = {
        "6621": (-0.08 * span_x, 0.0),
        "6608": (-0.06 * span_x, -0.06 * span_y),
        "6617": (0.07 * span_x, 0.03 * span_y),
        "6612": (0.09 * span_x, -0.03 * span_y),
        "6623": (-0.03 * span_x, 0.05 * span_y),
        "6634": (-0.07 * span_x, 0.04 * span_y),
        "6628": (-0.07 * span_x, -0.02 * span_y),
        "6643": (-0.06 * span_x, 0.03 * span_y),
        "6607": (-0.08 * span_x, 0.0),
        "6633": (-0.04 * span_x, -0.06 * span_y),
        "6645": (0.0, -0.06 * span_y),
        "6613": (0.10 * span_x, 0.0),
        "6640": (0.10 * span_x, -0.02 * span_y),
        "6642": (0.09 * span_x, 0.04 * span_y),
        "6616": (0.08 * span_x, 0.0),
        "6630": (-0.06 * span_x, 0.0),
        "6644": (0.0, 0.04 * span_y),
    }

    for gid, (cx, cy) in centroids.items():
        if gid not in lookup:
            continue
        med = lookup[gid]
        lbl = label_lookup.get(gid, "")
        short = (lbl.replace("Genève", "GE")
                    .replace("Grand-Saconnex", "Gd-Sac.")
                    .replace("Collonge-Bellerive", "Coll.-Bell.")
                    .replace("Chêne-Bougeries", "Ch.-Boug.")
                    .replace("Plan-les-Ouates", "Plan-l.-O.")
                    .replace("Pregny-Chambésy", "Pregny-Ch."))
        val_str = value_fmt(med)

        dx, dy = OFFSETS.get(gid, (0, 0))
        lx, ly = cx + dx, cy + dy

        ax.annotate("", xy=(cx, cy), xytext=(lx, ly + span_y * 0.012),
                     arrowprops={"arrowstyle": "-", "color": MUTED,
                                 "lw": 0.5, "alpha": 0.4},
                     zorder=7)
        ax.text(lx, ly + span_y * 0.018, short,
                ha="center", va="bottom", fontsize=8,
                color=INK, fontweight="bold", zorder=8)
        ax.text(lx, ly - span_y * 0.003, val_str,
                ha="center", va="top", fontsize=7.5,
                color=INK, zorder=8)

        if gid in prev_lookup:
            pct = (med / prev_lookup[gid] - 1) * 100
            if abs(pct) < 0.5:
                btxt, bfg, bbg = f"{pct:+.0f}%", "#57534E", "#E7E5E4"
            elif pct > 0:
                btxt, bfg, bbg = f"+{pct:.0f}%", "#166534", "#DCFCE7"
            else:
                btxt, bfg, bbg = f"{pct:.0f}%", "#B91C1C", "#FEE2E2"
            ax.text(lx, ly - span_y * 0.028, btxt,
                    ha="center", va="top", fontsize=7, color=bfg,
                    bbox={"boxstyle": "round,pad=0.2",
                          "facecolor": bbg, "edgecolor": "none"},
                    zorder=8)

    sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
    cb = fig.colorbar(sm, ax=ax, fraction=0.025, pad=0.01,
                      shrink=0.7, location="right")
    cb.ax.tick_params(labelsize=9, colors=MUTED)
    cb.set_label(c.get("ylabel", ""), fontsize=10, color=MUTED)
    if vmax > 100_000:
        cb.ax.yaxis.set_major_formatter(
            mticker.FuncFormatter(lambda x, _: f"{x/1e6:.1f}M"))

    fig.subplots_adjust(left=0.02, right=0.90, top=0.84, bottom=0.10)
    fig.text(0.01, 0.98, c["title"], fontsize=18, color=INK,
             fontweight="bold", va="top")
    fig.text(0.01, 0.91, c["subtitle"], fontsize=12, color=MUTED,
             va="top", style="italic")
    fig.text(0.91, 0.98, "2024", fontsize=12, color=MUTED,
             ha="right", va="top")
    fig.text(0.91, 0.93, "YoY vs 2023", fontsize=10, color=MUTED,
             ha="right", va="top")
    fig.text(0.01, 0.03, c["note"], fontsize=9, color=MUTED, va="top")
    return fig


def fig_map_apartments(gj: dict, price: pd.DataFrame, copy: dict) -> plt.Figure:
    c = ch(copy, "03b_map_apartments")
    cur = ppe_m2(price, geo=None, condition="existing", communes_only=True)
    data = cur[cur.year == 2024][["geo_id", "geo_label", "median", "n"]]
    prev = cur[cur.year == 2023][["geo_id", "geo_label", "median", "n"]]
    return _labeled_map(gj, data, prev, c, plt.cm.Blues,
                        lambda v: f"{v/1000:.1f}K", canton_med=None)


def fig_map_houses(gj: dict, price: pd.DataFrame, copy: dict) -> plt.Figure:
    c = ch(copy, "03c_map_houses")
    h = price[
        (price.source == "T_05_05_1_3_03")
        & (price.type_id.str.contains("house", na=False))
        & (price["median"].notna())
        & (price.geo_id.notna())
        & (price.geo_id != "0000")
    ].copy()
    data = h[h.year == 2024][["geo_id", "geo_label", "median", "n"]]
    prev = h[h.year == 2023][["geo_id", "geo_label", "median", "n"]]
    return _labeled_map(gj, data, prev, c, plt.cm.Oranges,
                        lambda v: f"{v/1e6:.1f}M", canton_med=None)


def _commune_range_chart(
    df_cur: pd.DataFrame,
    df_prev: pd.DataFrame | None,
    canton_med: float,
    c: dict,
    bar_color: str,
) -> plt.Figure:
    """Shared renderer for commune-level P25-P75 charts (04 and 04b)."""
    df = df_cur.sort_values("median").reset_index(drop=True)
    if df_prev is not None and len(df_prev):
        prev = df_prev[["geo_label", "median"]].rename(columns={"median": "med_prev"})
        df = df.merge(prev, on="geo_label", how="left")
    else:
        df["med_prev"] = pd.NA

    n_items = len(df)
    fig, ax = plt.subplots(figsize=(9.0, max(5.8, 0.52 * n_items + 2.0)))

    ax.axvline(canton_med, color=bar_color, linestyle="--",
               linewidth=1.2, alpha=0.5, zorder=1)
    ax.text(canton_med, -0.50,
            f"{c['vline_label']}  {fmt_int(canton_med)} CHF/m²",
            ha="center", va="top", fontsize=9, color=bar_color, style="italic")

    for i, row in df.iterrows():
        lo, mid, hi = row["p25"], row["median"], row["p75"]
        n = int(row["n"])
        label = f"{row['geo_label']}  (n={n})"
        ax.plot([lo, hi], [i, i], color=bar_color, linewidth=8,
                solid_capstyle="round", alpha=0.85)
        ax.scatter(mid, i, s=70, color="#FBBF24",
                   edgecolors="white", linewidths=1.0, zorder=4)
        ax.text(hi + 80, i + 0.05, f"{fmt_int(mid)}",
                va="center", fontsize=9, color=INK, fontweight="bold")

        if pd.notna(row.get("med_prev")):
            pct = (mid / row["med_prev"] - 1) * 100
            if abs(pct) < 0.05:
                btxt, bfg, bbg = f"{pct:.1f}%", "#57534E", "#E7E5E4"
            elif pct > 0:
                btxt, bfg, bbg = f"▲+{pct:.1f}%", "#166534", "#DCFCE7"
            else:
                btxt, bfg, bbg = f"▼{pct:.1f}%", "#B91C1C", "#FEE2E2"
            ax.annotate(btxt, xy=(hi + 80, i - 0.05),
                        xytext=(55, 0), textcoords="offset points",
                        ha="left", va="center", fontsize=8, color=bfg,
                        bbox={"boxstyle": "round,pad=0.25",
                              "facecolor": bbg, "edgecolor": "none"})

        ax.annotate(label, xy=(0, i), xycoords=("axes fraction", "data"),
                    xytext=(-8, 0), textcoords="offset points",
                    ha="right", va="center", fontsize=10, color=INK)

    ax.set_yticks([])
    style_ax(ax, xlabel=c["xlabel"], grid="")
    ax.grid(False)
    ax.set_ylim(-0.7, n_items + 0.2)
    pad = 250
    ax.set_xlim(df["p25"].min() - pad, df["p75"].max() + pad + 800)
    ax.xaxis.set_major_formatter(
        mticker.FuncFormatter(lambda x, _p: f"{fmt_int(x)}"))

    fig.subplots_adjust(left=0.20, right=0.97, top=0.82, bottom=0.16)
    fig.text(0.01, 0.98, c["title"], fontsize=18, color=INK,
             fontweight="bold", va="top")
    fig.text(0.01, 0.91, c["subtitle"], fontsize=12, color=MUTED,
             va="top", style="italic")
    fig.text(0.97, 0.98, "2024", fontsize=12, color=MUTED,
             ha="right", va="top")
    fig.text(0.97, 0.93, "YoY vs 2023", fontsize=10, color=MUTED,
             ha="right", va="top")
    fig.text(0.01, 0.04, c["note"], fontsize=10, color=MUTED, va="top")
    return fig


def fig_ppe_range(price: pd.DataFrame, copy: dict) -> plt.Figure:
    cur = ppe_m2(price, geo=None, condition="existing", communes_only=True)
    cur24 = cur[cur.year == 2024].copy()
    prev23 = cur[cur.year == 2023].copy()
    canton_med = float(
        ppe_m2(price, geo="0000", condition="existing")
        .loc[lambda d: d.year == 2024, "median"].iloc[0])
    c = ch(copy, "04_ppe_range")
    return _commune_range_chart(cur24, prev23, canton_med, c, PPE)


def fig_new_vs_existing_commune(price: pd.DataFrame, copy: dict) -> plt.Figure:
    c = ch(copy, "04c_new_vs_existing_commune")
    ex = ppe_m2(price, geo=None, condition="existing", communes_only=True)
    nw = ppe_m2(price, geo=None, condition="new", communes_only=True)
    ex24 = ex[ex.year == 2024][["geo_label", "median", "n"]].rename(
        columns={"median": "med_ex", "n": "n_ex"})
    nw24 = nw[nw.year == 2024][["geo_label", "median", "n"]].rename(
        columns={"median": "med_nw", "n": "n_nw"})
    df = ex24.merge(nw24, on="geo_label")
    df["prem_pct"] = (df["med_nw"] / df["med_ex"] - 1) * 100
    df = df.sort_values("med_ex").reset_index(drop=True)

    n_items = len(df)
    fig, ax = plt.subplots(figsize=(9.0, max(5.0, 0.9 * n_items + 2.5)))

    for i, row in df.iterrows():
        ax.plot([row["med_ex"], row["med_nw"]], [i, i],
                color=LINE, linewidth=2.5, zorder=1)
        ax.scatter(row["med_ex"], i, s=100, color=PPE, edgecolors="white",
                   linewidths=1.2, zorder=3)
        ax.scatter(row["med_nw"], i, s=100, color=NEW, edgecolors="white",
                   linewidths=1.2, zorder=3)
        ax.text(row["med_ex"], i - 0.22,
                f"{fmt_int(row['med_ex'])}  (n={int(row['n_ex'])})",
                ha="center", va="top", fontsize=9, color=PPE)
        ax.text(row["med_nw"], i - 0.22,
                f"{fmt_int(row['med_nw'])}  (n={int(row['n_nw'])})",
                ha="center", va="top", fontsize=9, color=NEW)
        pct = row["prem_pct"]
        ax.annotate(
            f"+{pct:.0f}%",
            xy=((row["med_ex"] + row["med_nw"]) / 2, i),
            xytext=(0, 14), textcoords="offset points",
            ha="center", va="bottom", fontsize=11, color="#166534",
            fontweight="bold",
            bbox={"boxstyle": "round,pad=0.3",
                  "facecolor": "#DCFCE7", "edgecolor": "none"})

    ax.scatter([], [], s=60, color=PPE, label=c["label_existing"])
    ax.scatter([], [], s=60, color=NEW, label=c["label_new"])
    ax.legend(loc="upper left", frameon=False, fontsize=10,
              handletextpad=0.4, columnspacing=1.2, ncols=2)

    labels = df["geo_label"].tolist()
    ax.set_yticks(list(range(n_items)), labels, fontsize=12)
    style_ax(ax, xlabel=c["xlabel"], grid="")
    ax.grid(False)
    ax.set_ylim(-0.6, n_items + 0.1)
    pad = 400
    ax.set_xlim(df["med_ex"].min() - pad, df["med_nw"].max() + pad)
    ax.xaxis.set_major_formatter(
        mticker.FuncFormatter(lambda x, _p: f"{fmt_int(x)}"))

    fig.subplots_adjust(left=0.18, right=0.97, top=0.80, bottom=0.18)
    fig.text(0.01, 0.98, c["title"], fontsize=18, color=INK,
             fontweight="bold", va="top")
    fig.text(0.01, 0.91, c["subtitle"], fontsize=11, color=MUTED,
             va="top", style="italic")
    ax.text(0.98, 0.99, "2024", transform=ax.transAxes,
            fontsize=12, color=MUTED, ha="right", va="top")
    fig.text(0.01, 0.04, c["note"], fontsize=10, color=MUTED, va="top")
    return fig


def fig_ppe_range_new(price: pd.DataFrame, copy: dict) -> plt.Figure:
    cur = ppe_m2(price, geo=None, condition="new", communes_only=True)
    cur24 = cur[cur.year == 2024].copy()
    prev23 = cur[cur.year == 2023].copy()
    canton_nw = ppe_m2(price, geo="0000", condition="new")
    canton_nw24 = canton_nw[canton_nw.year == 2024]
    canton_med = float(canton_nw24["median"].iloc[0]) if len(canton_nw24) else float(cur24["median"].mean())
    c = ch(copy, "04b_ppe_range_new")
    return _commune_range_chart(cur24, prev23, canton_med, c, NEW)


def fig_premium_vs_canton(price: pd.DataFrame, copy: dict) -> plt.Figure:
    canton = float(ppe_m2(price).loc[lambda d: d.year == 2024, "median"].iloc[0])
    df = ppe_m2(price, geo=None, communes_only=True)
    df = df[df.year == 2024].copy()
    df["prem"] = 100 * (df["median"] / canton - 1)
    df = df.sort_values("prem")
    colors = [POS if x >= 0 else NEG for x in df["prem"]]
    c = ch(copy, "05_premium_vs_canton")
    fig, ax = plt.subplots(figsize=(10.2, 6.4))
    y = list(range(len(df)))
    ax.barh(y, df["prem"], color=colors, height=0.72)
    ax.axvline(0, color=INK, linewidth=1.0)
    ax.set_yticks(y, df["geo_label"].astype(str))
    style_ax(ax, xlabel=c["xlabel"], grid="x")
    ax.grid(axis="y", visible=False)
    title(ax, c["title"])
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: f"{x:+.0f}"))
    fig.subplots_adjust(left=0.22, right=0.97, top=0.88, bottom=0.18)
    caption(fig, c["note"], derived=True)
    return fig


def fig_ppe_new_vs_existing(price: pd.DataFrame, copy: dict) -> plt.Figure:
    ex = ppe_m2(price, condition="existing")
    nw = ppe_m2(price, condition="new")
    c = ch(copy, "06_ppe_new_vs_existing")
    fig, ax = plt.subplots(figsize=(10.2, 5.7))
    ax.plot(ex.year, ex["median"], color=PPE, linewidth=2.4, label=c["legend_existing"])
    ax.plot(nw.year, nw["median"], color=NEW, linewidth=2.2, label=c["legend_new"])
    style_ax(ax, c["ylabel"])
    title(ax, c["title"])
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
    year_axis(ax)
    fig.subplots_adjust(left=0.12, right=0.97, top=0.86, bottom=0.20)
    caption(fig, c["note"])
    return fig


def fig_apartments_2024_quartiles(price: pd.DataFrame, copy: dict) -> plt.Figure:
    c = ch(copy, "06b_apartments_2024_quartiles")
    ex = ppe_m2(price, geo="0000", condition="existing", market="libre")
    nw = ppe_m2(price, geo="0000", condition="new", market="libre")
    df = pd.concat([ex, nw], ignore_index=True)

    cur = df[df.year == 2024][["condition", "n", "p25", "median", "p75"]].copy()
    prev = df[df.year == 2023][["condition", "median"]].rename(columns={"median": "median_prev"})
    cur = cur.merge(prev, on="condition", how="left")
    cur["yoy_pct"] = (cur["median"] / cur["median_prev"] - 1) * 100

    canton_all = ppe_m2(price, geo="0000", condition="all", market="libre")
    canton_all_2024 = canton_all[canton_all.year == 2024]
    canton_med = float(canton_all_2024["median"].iloc[0]) if len(canton_all_2024) else float(cur["median"].mean())

    cur = cur.set_index("condition").loc[["new", "existing"]].reset_index()

    colors = {"existing": PPE, "new": NEW}
    labels = {
        row["condition"]: f"{c['label_' + row['condition']]}\n(n={fmt_int(row['n'])})"
        for _, row in cur.iterrows()
    }

    fig, ax = plt.subplots(figsize=(9.0, 5.8))

    ax.axvline(canton_med, color=MUTED, linestyle="--", linewidth=1.2, alpha=0.6, zorder=1)
    ax.text(canton_med, 1.58, f"{c['canton_label']}\n{fmt_int(canton_med)} CHF/m²",
            ha="center", va="bottom", fontsize=10, color=MUTED, style="italic")

    for i, row in cur.iterrows():
        lo, mid, hi = row["p25"], row["median"], row["p75"]
        color = colors[row["condition"]]
        ax.plot([lo, hi], [i, i], color=color, linewidth=12,
                solid_capstyle="round", alpha=0.92)
        ax.scatter(mid, i, s=110, color="#FBBF24",
                   edgecolors="white", linewidths=1.3, zorder=4)
        ax.text(lo, i - 0.24, f"{fmt_int(lo)}",
                ha="center", va="top", fontsize=14, color=MUTED)
        ax.text(hi, i - 0.24, f"{fmt_int(hi)}",
                ha="center", va="top", fontsize=14, color=MUTED)
        ax.text(mid, i + 0.22, f"{fmt_int(mid)} CHF/m²",
                ha="right", va="bottom", fontsize=18, color=INK, fontweight="bold")

        pct = float(row["yoy_pct"])
        if abs(pct) < 0.05:
            badge_txt, badge_fg, badge_bg = f"{pct:.1f}% YoY", "#57534E", "#E7E5E4"
        elif pct > 0:
            badge_txt, badge_fg, badge_bg = f"▲ +{pct:.1f}% YoY", "#166534", "#DCFCE7"
        else:
            badge_txt, badge_fg, badge_bg = f"▼ {pct:.1f}% YoY", "#B91C1C", "#FEE2E2"
        ax.annotate(badge_txt, xy=(mid, i + 0.22), xytext=(12, 0),
                    textcoords="offset points", ha="left", va="bottom",
                    fontsize=12, color=badge_fg,
                    bbox={"boxstyle": "round,pad=0.3",
                           "facecolor": badge_bg, "edgecolor": "none"})

    ax.set_yticks(list(range(len(cur))),
                  [labels[cond] for cond in cur["condition"]], fontsize=15)
    style_ax(ax, xlabel=c["xlabel"], grid="")
    ax.grid(False)
    ax.set_ylim(-0.62, 1.78)
    pad = 300
    ax.set_xlim(cur["p25"].min() - pad, cur["p75"].max() + pad)
    ax.xaxis.set_major_formatter(
        mticker.FuncFormatter(lambda x, _p: f"{fmt_int(x)}"))

    fig.subplots_adjust(left=0.22, right=0.97, top=0.76, bottom=0.22)
    fig.text(0.01, 0.98, c["title"], fontsize=20, color=INK,
             fontweight="bold", va="top")
    fig.text(0.01, 0.89, c["subtitle"], fontsize=13, color=MUTED,
             va="top", style="italic")
    ax.text(0.98, 0.98, "2024", transform=ax.transAxes,
            fontsize=13, color=MUTED, ha="right", va="top")
    ax.text(0.98, 0.88, "YoY vs 2023", transform=ax.transAxes,
            fontsize=11, color=MUTED, ha="right", va="top")
    fig.text(0.01, 0.06, c["note"], fontsize=10, color=MUTED, va="top")
    return fig


def fig_new_build_premium(price: pd.DataFrame, copy: dict) -> plt.Figure:
    ex = ppe_m2(price, condition="existing")[["year", "median"]].rename(columns={"median": "existing"})
    nw = ppe_m2(price, condition="new")[["year", "median"]].rename(columns={"median": "new"})
    m = ex.merge(nw, on="year")
    m["prem"] = 100 * (m["new"] / m["existing"] - 1)
    c = ch(copy, "07_new_build_premium")
    fig, ax = plt.subplots(figsize=(10.2, 5.7))
    ax.axhline(0, color=INK, linewidth=1.0)
    ax.plot(m.year, m["prem"], color=NEW, linewidth=2.3)
    style_ax(ax, c["ylabel"])
    title(ax, c["title"])
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: f"{x:+.0f}"))
    year_axis(ax)
    fig.subplots_adjust(left=0.12, right=0.97, top=0.86, bottom=0.20)
    caption(fig, c["note"], derived=True)
    return fig


def fig_price_vs_cagr(price: pd.DataFrame, copy: dict, params: dict) -> plt.Figure:
    years = int(params.get("cagr_years", 10))
    end = 2024
    start = end - years
    base = ppe_m2(price, geo=None, communes_only=True)
    a = base[base.year == start][["geo_id", "geo_label", "median"]].rename(columns={"median": "p0"})
    b = base[base.year == end][["geo_id", "median"]].rename(columns={"median": "p1"})
    m = a.merge(b, on="geo_id")
    m["cagr"] = 100 * ((m["p1"] / m["p0"]) ** (1 / years) - 1)
    c = ch(copy, "08_price_vs_cagr")
    fig, ax = plt.subplots(figsize=(10.2, 6.2))
    ax.scatter(m["p1"], m["cagr"], color=PPE, s=42, zorder=3)
    for _, row in m.iterrows():
        ax.annotate(
            str(row["geo_label"]),
            (row["p1"], row["cagr"]),
            textcoords="offset points",
            xytext=(5, 3),
            fontsize=8,
            color=MUTED,
        )
    style_ax(ax, ylabel=c["ylabel"], xlabel=c["xlabel"], grid="both")
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: f"{x:.1f}"))
    fig.subplots_adjust(left=0.11, right=0.97, top=0.82, bottom=0.16)
    fig.text(0.01, 0.98, c["title"], fontsize=17, color=INK,
             fontweight="bold", va="top")
    fig.text(0.01, 0.06, c["note"], fontsize=10, color=MUTED, va="top")
    return fig


def fig_volume_activity(vol: pd.DataFrame, copy: dict) -> plt.Figure:
    y = vol[(vol.freq == "Y") & (vol.is_provisional == 0) & (vol.year >= 2010) & (vol.year <= 2024)]
    c = ch(copy, "10_volume_activity")
    fig, ax = plt.subplots(figsize=(10.2, 5.7))
    for tid, color, key in (("ppe", PPE, "legend_ppe"), ("house", HOUSE, "legend_house")):
        s = y[y.type_id == tid].sort_values("year")
        ax.plot(s.year, s["n"], color=color, linewidth=2.3, label=c[key])
    style_ax(ax, c["ylabel"])
    title(ax, c["title"])
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
    year_axis(ax)
    fig.subplots_adjust(left=0.11, right=0.97, top=0.86, bottom=0.20)
    caption(fig, c["note"])
    return fig


def fig_volume_new_existing(vol: pd.DataFrame, copy: dict) -> plt.Figure:
    y = vol[(vol.freq == "Y") & (vol.is_provisional == 0) & (vol.year >= 2010) & (vol.year <= 2024)]
    wide = y.pivot_table(index="year", columns="type_id", values="n")
    years = wide.index.to_numpy()
    c = ch(copy, "11_volume_new_existing")
    fig, axes = plt.subplots(1, 2, figsize=(11.2, 5.5), sharey=True)
    specs = (
        (axes[0], c["ppe_panel"], "ppe_existing", "ppe_new", PPE, "#93C5FD"),
        (axes[1], c["house_panel"], "house_existing", "house_new", HOUSE, "#FDBA74"),
    )
    for ax, panel, ex, nw, col_ex, col_new in specs:
        ax.bar(years, wide[ex], color=col_ex, width=0.72, label=c["legend_ex"])
        ax.bar(years, wide[nw], bottom=wide[ex], color=col_new, width=0.72, label=c["legend_new"])
        style_ax(ax, c["ylabel"] if ax is axes[0] else None)
        ax.set_title(panel, loc="left", color=INK, fontsize=11, fontweight="bold", pad=8)
        ax.legend(frameon=False, fontsize=8, loc="upper left")
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
        year_axis(ax)
    fig.suptitle(c["title"], x=0.01, ha="left", color=INK, fontsize=13, fontweight="bold", y=0.98)
    fig.subplots_adjust(left=0.08, right=0.98, top=0.82, bottom=0.18, wspace=0.18)
    caption(fig, c["note"])
    return fig


def fig_quarterly_pulse(price: pd.DataFrame, vol: pd.DataFrame, copy: dict, params: dict) -> plt.Figure:
    start = int(params.get("quarterly_from", 2017))
    qn = vol[(vol.freq == "Q") & (vol.is_provisional == 0) & (vol.year >= start) & (vol.year <= 2024)].copy()
    qp = price[
        (price.source == "T_05_05_1_1_02")
        & (price.is_provisional == 0)
        & (price.year >= start)
        & (price.year <= 2024)
        & price["median"].notna()
    ].copy()
    for df in (qn, qp):
        df["t"] = df["year"] + (df["quarter"] - 0.5) / 4
    c = ch(copy, "12_quarterly_pulse")
    fig, axes = plt.subplots(2, 1, figsize=(10.2, 7.6), sharex=True)
    for tid, color, key in (("ppe", PPE, "legend_ppe"), ("house", HOUSE, "legend_house")):
        s = qn[qn.type_id == tid].sort_values(["year", "quarter"])
        axes[0].plot(s["t"], s["n"], color=color, linewidth=1.8, label=c[key])
    for tid, color, key in (("ppe_existing", PPE, "legend_ppe"), ("house_existing", HOUSE, "legend_house")):
        s = qp[qp.type_id == tid].sort_values(["year", "quarter"])
        axes[1].plot(s["t"], s["median"] / 1e6, color=color, linewidth=1.8, label=c[key])
    style_ax(axes[0], c["ylabel_n"])
    style_ax(axes[1], c["ylabel_px"])
    title(axes[0], c["title"])
    axes[0].legend(frameon=False, fontsize=8, loc="upper left", ncol=2)
    axes[1].legend(frameon=False, fontsize=8, loc="upper left", ncol=2)
    axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
    year_axis(axes[1])
    fig.subplots_adjust(left=0.11, right=0.97, top=0.90, bottom=0.16, hspace=0.18)
    caption(fig, c["note"])
    return fig


def fig_house_ticket(price: pd.DataFrame, copy: dict) -> plt.Figure:
    df = house_object(price, geo=None, communes_only=True)
    df = df[df.year == 2024].sort_values("median")
    c = ch(copy, "13_house_ticket")
    fig, ax = plt.subplots(figsize=(10.2, 6.8))
    plot_interval(ax, df, color=HOUSE, xcols=("p25", "median", "p75"), scale=1e6)
    style_ax(ax, xlabel=c["xlabel"], grid="x")
    ax.grid(axis="y", visible=False)
    title(ax, c["title"])
    fig.subplots_adjust(left=0.24, right=0.97, top=0.88, bottom=0.18)
    caption(fig, c["note"])
    return fig


def fig_q_latest_existing_range(price: pd.DataFrame, vol: pd.DataFrame, copy: dict) -> plt.Figure:
    year, quarter = latest_quarter(price, vol)
    yoy_y, yoy_q = year - 1, quarter
    c = ch(copy, "14_q_latest_existing_range")
    df = existing_range_quarter(price, year, quarter)
    prev = existing_range_quarter(price, yoy_y, yoy_q).rename(columns={"median": "median_prev"})
    df = df.merge(prev[["type_id", "median_prev"]], on="type_id", how="left")
    df["yoy_pct"] = (df["median"] / df["median_prev"] - 1) * 100

    house = df.loc[df.type_id == "house_existing"].iloc[0]
    apt = df.loc[df.type_id == "ppe_existing"].iloc[0]

    colors = {"house_existing": "#059669", "ppe_existing": "#3B82F6"}
    labels = {
        "house_existing": f"{c['label_house']}\n(n={fmt_int(house['n'])})",
        "ppe_existing": f"{c['label_ppe']}\n(n={fmt_int(apt['n'])})",
    }

    fig, ax = plt.subplots(figsize=(9.0, 5.8))
    for i, row in df.iterrows():
        lo, mid, hi = row["p25"] / 1e6, row["median"] / 1e6, row["p75"] / 1e6
        color = colors[row["type_id"]]
        ax.plot([lo, hi], [i, i], color=color, linewidth=12, solid_capstyle="round", alpha=0.92)
        ax.scatter(mid, i, s=110, color="#FBBF24", edgecolors="white", linewidths=1.3, zorder=4)
        ax.text(lo, i - 0.24, f"{lo:.2f}M", ha="center", va="top", fontsize=14, color=MUTED)
        ax.text(hi, i - 0.24, f"{hi:.2f}M", ha="center", va="top", fontsize=14, color=MUTED)
        ax.text(
            mid,
            i + 0.22,
            f"{mid:.2f}M CHF",
            ha="right",
            va="bottom",
            fontsize=18,
            color=INK,
            fontweight="bold",
        )
        pct = float(row["yoy_pct"])
        if abs(pct) < 0.05:
            badge_txt, badge_fg, badge_bg = f"{pct:.1f}% YoY", "#57534E", "#E7E5E4"
        elif pct > 0:
            badge_txt, badge_fg, badge_bg = f"▲ +{pct:.1f}% YoY", "#166534", "#DCFCE7"
        else:
            badge_txt, badge_fg, badge_bg = f"▼ {pct:.1f}% YoY", "#B91C1C", "#FEE2E2"
        ax.annotate(
            badge_txt,
            xy=(mid, i + 0.22),
            xytext=(12, 0),
            textcoords="offset points",
            ha="left",
            va="bottom",
            fontsize=12,
            color=badge_fg,
            bbox={"boxstyle": "round,pad=0.3", "facecolor": badge_bg, "edgecolor": "none"},
        )
    ax.set_yticks(list(range(len(df))), [labels[t] for t in df["type_id"]], fontsize=15)
    style_ax(ax, xlabel=c["xlabel"], grid="")
    ax.grid(False)
    ax.set_ylim(-0.62, 1.68)
    pad = 0.22
    ax.set_xlim(df["p25"].min() / 1e6 - pad, df["p75"].max() / 1e6 + pad)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: f"{x:.1f}M"))
    fig.subplots_adjust(left=0.22, right=0.97, top=0.76, bottom=0.22)
    fig.text(0.01, 0.98, c["title"], fontsize=20, color=INK, fontweight="bold", va="top")
    fig.text(0.01, 0.89, c["subtitle"], fontsize=13, color=MUTED, va="top", style="italic")
    ax.text(0.98, 0.98, f"Q{quarter} {year}", transform=ax.transAxes,
            fontsize=13, color=MUTED, ha="right", va="top")
    ax.text(0.98, 0.88, f"YoY vs Q{yoy_q} {yoy_y}", transform=ax.transAxes,
            fontsize=11, color=MUTED, ha="right", va="top")
    fig.text(0.01, 0.06, c["note"].format(prev_q=f"Q{yoy_q} {yoy_y}"),
             fontsize=10, color=MUTED, va="top")
    return fig


def fig_price_vs_n(price: pd.DataFrame, copy: dict) -> plt.Figure:
    df = ppe_m2(price, geo=None, communes_only=True)
    df = df[df.year == 2024]
    c = ch(copy, "15_price_vs_n")
    fig, ax = plt.subplots(figsize=(10.2, 6.2))
    ax.scatter(df["median"], df["n"], color=PPE, s=42, zorder=3)
    for _, row in df.iterrows():
        ax.annotate(
            str(row["geo_label"]),
            (row["median"], row["n"]),
            textcoords="offset points",
            xytext=(5, 3),
            fontsize=8,
            color=MUTED,
        )
    style_ax(ax, ylabel=c["ylabel"], xlabel=c["xlabel"], grid="both")
    title(ax, c["title"])
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
    fig.subplots_adjust(left=0.12, right=0.97, top=0.86, bottom=0.20)
    caption(fig, c["note"], derived=True)
    return fig


def fig_market_shocks(price: pd.DataFrame, vol: pd.DataFrame, copy: dict) -> plt.Figure:
    ppe = ppe_m2(price).sort_values("year")
    ppe = ppe.assign(yoy=ppe["median"].pct_change() * 100)
    n_ppe = vol[(vol.freq == "Y") & (vol.is_provisional == 0) & (vol.type_id == "ppe")].sort_values("year")
    n_ppe = n_ppe.assign(yoy=n_ppe["n"].pct_change() * 100)
    house = house_object(price).sort_values("year")
    house = house.assign(yoy=house["median"].pct_change() * 100)
    ppe = ppe[ppe.year >= 2006]
    n_ppe = n_ppe[n_ppe.year >= 2006]
    house = house[house.year >= 2006]
    c = ch(copy, "17_market_shocks")
    fig, axes = plt.subplots(3, 1, figsize=(10.2, 8.6), sharex=True)
    series = (
        (axes[0], ppe, "yoy", c["ylabel_ppe"], PPE),
        (axes[1], n_ppe, "yoy", c["ylabel_n"], NEW),
        (axes[2], house, "yoy", c["ylabel_house"], HOUSE),
    )
    for ax, df, col, ylab, color in series:
        d = df.dropna(subset=[col])
        ax.bar(d.year, d[col], color=color, width=0.78, alpha=0.9)
        ax.axhline(0, color=INK, linewidth=0.8)
        for yr in (2008, 2020, 2022):
            ax.axvline(yr, color=LINE, linewidth=1.1, linestyle="--")
        style_ax(ax, ylab)
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: f"{x:+.0f}"))
        year_axis(ax)
        ax.set_xlim(2005.5, 2024.5)
    title(axes[0], c["title"])
    fig.subplots_adjust(left=0.14, right=0.97, top=0.92, bottom=0.12, hspace=0.18)
    caption(fig, c["note"], derived=True)
    return fig


def fig_libre_vs_zd(price: pd.DataFrame, copy: dict) -> plt.Figure:
    libre = ppe_m2(price, condition="all", market="libre")
    zd = ppe_m2(price, condition="all", market="zd")
    c = ch(copy, "18_libre_vs_zd")
    fig, ax = plt.subplots(figsize=(10.2, 5.7))
    ax.plot(libre.year, libre["median"], color=PPE, linewidth=2.4, label=c["legend_libre"])
    ax.plot(zd.year, zd["median"], color=ZD, linewidth=2.2, label=c["legend_zd"])
    style_ax(ax, c["ylabel"])
    title(ax, c["title"])
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _p: fmt_int(x)))
    year_axis(ax)
    fig.subplots_adjust(left=0.12, right=0.97, top=0.86, bottom=0.20)
    caption(fig, c["note"])
    return fig


def fig_budget_area(price: pd.DataFrame, copy: dict, params: dict) -> plt.Figure:
    budget = float(params.get("budget_chf", 800_000))
    df = ppe_m2(price, geo=None, communes_only=True)
    df = df[df.year == 2024].copy()
    canton = ppe_m2(price)
    canton = canton[canton.year == 2024].iloc[0]
    extra = pd.DataFrame(
        {
            "geo_label": ["Canton (benchmark)"],
            "median": [float(canton["median"])],
        }
    )
    df = pd.concat([df[["geo_label", "median"]], extra], ignore_index=True)
    df["area"] = budget / df["median"]
    df = df.sort_values("area")
    c = ch(copy, "19_budget_area")
    fig, ax = plt.subplots(figsize=(10.2, 6.6))
    y = list(range(len(df)))
    colors = [MUTED if str(lbl).startswith("Canton") else PPE for lbl in df["geo_label"]]
    ax.barh(y, df["area"], color=colors, height=0.72)
    ax.set_yticks(y, df["geo_label"].astype(str))
    style_ax(ax, xlabel=c["xlabel"], grid="x")
    ax.grid(axis="y", visible=False)
    title(ax, c["title"])
    fig.subplots_adjust(left=0.24, right=0.97, top=0.88, bottom=0.18)
    caption(fig, c["note"], derived=True)
    return fig


def fig_quarterly_corridor(price: pd.DataFrame, copy: dict) -> plt.Figure:
    """Two-panel quarterly chart: apartments + houses with P25-P75 band."""
    c = ch(copy, "21_quarterly_corridor")
    q = price[
        (price.source == "T_05_05_1_1_02")
        & (price.geo_id == "0000")
        & (price["median"].notna())
    ].copy()
    q["t"] = q.year + (q.quarter - 1) / 4

    apt = q[q.type_id == "ppe_existing"].sort_values("t")
    hou = q[q.type_id == "house_existing"].sort_values("t")

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10.2, 8.0), sharex=True)

    for ax, df, color, band_c, ylabel in [
        (ax1, apt, PPE, BAND, c["ylabel_apt"]),
        (ax2, hou, HOUSE, "#FED7AA", c["ylabel_house"]),
    ]:
        med_m = df["median"] / 1e6
        p25_m = df.p25 / 1e6
        p75_m = df.p75 / 1e6
        ax.fill_between(df.t, p25_m, p75_m, color=band_c, linewidth=0, alpha=0.7)
        ax.plot(df.t, med_m, color=color, linewidth=2.0)
        style_ax(ax, ylabel)
        ax.tick_params(labelsize=10)

        peak = med_m.cummax()
        drawdown = (med_m.values - peak.values) / peak.values * 100
        max_dd = drawdown.min()
        dd_idx = int(drawdown.argmin())
        dd_t = df.t.iloc[dd_idx]
        dd_val = med_m.iloc[dd_idx]

        ax.annotate(
            f"max drawdown {max_dd:.0f}%",
            xy=(dd_t, dd_val), xytext=(15, -20),
            textcoords="offset points", fontsize=9, color="#B91C1C",
            arrowprops={"arrowstyle": "->", "color": "#B91C1C", "lw": 1},
            bbox={"boxstyle": "round,pad=0.3", "facecolor": "#FEE2E2",
                  "edgecolor": "none"},
        )

    ax2.set_xlabel("")
    years = sorted(set(int(y) for y in q.t if y == int(y)))
    ax2.set_xticks([y for y in years if y % 2 == 0])
    ax2.set_xticklabels([str(y) for y in years if y % 2 == 0])

    fig.subplots_adjust(left=0.10, right=0.97, top=0.86, bottom=0.10,
                        hspace=0.18)
    fig.text(0.01, 0.98, c["title"], fontsize=17, color=INK,
             fontweight="bold", va="top")
    fig.text(0.01, 0.03, c["note"], fontsize=10, color=MUTED, va="top")
    return fig


def fig_houses_trend(price: pd.DataFrame, copy: dict) -> plt.Figure:
    s = house_object(price)
    c = ch(copy, "20_houses_trend")
    fig, ax = plt.subplots(figsize=(10.2, 5.7))
    ax.fill_between(s.year, s.p25 / 1e6, s.p75 / 1e6, color="#FED7AA", linewidth=0, label=c["legend_iqr"])
    ax.plot(s.year, s["median"] / 1e6, color=HOUSE, linewidth=2.4, label=c["legend_median"])
    style_ax(ax, c["ylabel"])
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    year_axis(ax)
    ax.set_xlim(int(s.year.min()) - 0.5, int(s.year.max()) + 0.5)
    fig.subplots_adjust(left=0.08, right=0.97, top=0.82, bottom=0.16)
    fig.text(0.01, 0.98, c["title"], fontsize=17, color=INK,
             fontweight="bold", va="top")
    fig.text(0.01, 0.06, c["note"], fontsize=10, color=MUTED, va="top")
    return fig


def save_chart(fig: plt.Figure, name: str) -> Path:
    FIGURES.mkdir(parents=True, exist_ok=True)
    path = FIGURES / f"{name}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight", pad_inches=0.18)
    plt.close(fig)
    return path


def write_notes(k: dict, copy: dict, exported: list[str]) -> Path:
    lines = [
        "# PDF layout notes",
        "",
        "Figures: `exports/figures/*.png` (300 dpi).",
        "Change titles/captions in `exports/brief_copy.json`, then `python scripts/viz.py`.",
        "Layout in **Google Slides / PowerPoint**, A4 landscape, File → Download as PDF.",
        "",
        "P2 skipped (indexed commune trends, house map, historical stability).",
        "Budget chart uses `params.budget_chf`. CAGR uses `params.cagr_years`.",
        "",
        f"## {copy['title']}",
        "",
        copy["subtitle"],
        "",
        "## KPI",
        "",
        f"- {fmt_int(k['canton_m2'])} CHF/m2 — {copy['kpi']['left_caption']}",
        f"- {fmt_int(k['city_m2'])} CHF/m2 — {copy['kpi']['mid_caption']}",
        f"- +{k['premium_pct']:.1f}% — {copy['kpi']['right_caption']}",
        "",
        "## Callout",
        "",
        copy["callout"],
        "",
        "## Conclusions",
        "",
    ]
    for i, text in enumerate(copy["conclusions"], 1):
        lines.append(f"{i}. {text}")
    lines += ["", "## Chart library", ""]
    for name in exported:
        lines.append(f"- `{name}.png`")
    lines += ["", "## Footer", "", copy["footer"], "", copy["tech_line"], ""]
    path = EXPORTS / "brief_notes.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main() -> int:
    setup_mpl()
    d = load()
    params = d["copy"].get("params", {})
    k = kpis(d["price"], d["vol"], params)
    copy = fill_copy(d["copy"], k)
    FIGURES.mkdir(parents=True, exist_ok=True)
    for stem in OLD_PNG:
        p = FIGURES / f"{stem}.png"
        if p.exists():
            p.unlink()
        p = FIGURES / f"{stem}.pdf"
        if p.exists():
            p.unlink()

    exported: list[str] = []

    def dump(fig: plt.Figure, name: str) -> None:
        save_chart(fig, name)
        exported.append(name)

    dump(fig_ppe_trend(d["price"], copy), "01_ppe_trend")
    dump(fig_city_vs_canton(d["price"], copy), "02_city_vs_canton")
    dump(fig_ppe_map(d["gj"], d["price"], copy), "03_ppe_map")
    dump(fig_map_apartments(d["gj"], d["price"], copy), "03b_map_apartments")
    dump(fig_map_houses(d["gj"], d["price"], copy), "03c_map_houses")
    dump(fig_ppe_range(d["price"], copy), "04_ppe_range")
    dump(fig_ppe_range_new(d["price"], copy), "04b_ppe_range_new")
    dump(fig_new_vs_existing_commune(d["price"], copy), "04c_new_vs_existing_commune")
    dump(fig_premium_vs_canton(d["price"], copy), "05_premium_vs_canton")
    dump(fig_ppe_new_vs_existing(d["price"], copy), "06_ppe_new_vs_existing")
    dump(fig_apartments_2024_quartiles(d["price"], copy), "06b_apartments_2024_quartiles")
    dump(fig_new_build_premium(d["price"], copy), "07_new_build_premium")
    dump(fig_price_vs_cagr(d["price"], copy, params), "08_price_vs_cagr")
    dump(fig_q_latest_avg_ticket(d["price"], d["vol"], copy), "09_q_latest_avg_ticket")
    dump(fig_volume_activity(d["vol"], copy), "10_volume_activity")
    dump(fig_volume_new_existing(d["vol"], copy), "11_volume_new_existing")
    dump(fig_quarterly_pulse(d["price"], d["vol"], copy, params), "12_quarterly_pulse")
    dump(fig_house_ticket(d["price"], copy), "13_house_ticket")
    dump(fig_q_latest_existing_range(d["price"], d["vol"], copy), "14_q_latest_existing_range")
    dump(fig_price_vs_n(d["price"], copy), "15_price_vs_n")
    dump(fig_market_shocks(d["price"], d["vol"], copy), "17_market_shocks")
    dump(fig_libre_vs_zd(d["price"], copy), "18_libre_vs_zd")
    dump(fig_budget_area(d["price"], copy, params), "19_budget_area")
    dump(fig_houses_trend(d["price"], copy), "20_houses_trend")
    dump(fig_quarterly_corridor(d["price"], copy), "21_quarterly_corridor")

    notes = write_notes(k, copy, exported)
    print(f"Figures -> {FIGURES}  (png x {len(exported)})")
    print(f"Notes   -> {notes}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
